//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aspose.StaffManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aspose.StaffManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2300.
        /// </summary>
        internal static string BaseSalary {
            get {
                return ResourceManager.GetString("BaseSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string EmployeeMaxSalaryPercent {
            get {
                return ResourceManager.GetString("EmployeeMaxSalaryPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string EmployeeSalaryPerYearPercent {
            get {
                return ResourceManager.GetString("EmployeeSalaryPerYearPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40.
        /// </summary>
        internal static string ManagerMaxSalaryPercent {
            get {
                return ResourceManager.GetString("ManagerMaxSalaryPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string ManagerSalaryPerYearPercent {
            get {
                return ResourceManager.GetString("ManagerSalaryPerYearPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.5.
        /// </summary>
        internal static string ManagerSubordinatesSalaryPercent {
            get {
                return ResourceManager.GetString("ManagerSubordinatesSalaryPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        internal static string SalesMaxSalaryPercent {
            get {
                return ResourceManager.GetString("SalesMaxSalaryPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string SalesSalaryPerYearPercent {
            get {
                return ResourceManager.GetString("SalesSalaryPerYearPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.3.
        /// </summary>
        internal static string SalesSubordinatesSalaryPercent {
            get {
                return ResourceManager.GetString("SalesSubordinatesSalaryPercent", resourceCulture);
            }
        }
    }
}
